version: 0.2
env:
  shell: bash
  variables:
    CF_ORG_RULESET:  "serverless-guard-check"
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - pip install --upgrade aws-sam-cli
      # To install cfn-guard
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup.sh
      - chmod 755 rustup.sh
      - ./rustup.sh -y
      - source $HOME/.cargo/env
      - cargo install cfn-guard
      - aws configure set region $AWS_DEFAULT_REGION
      - sudo apt-get update
      - sudo apt-get install uuid-runtime
      - sudo apt-get -y install coreutils
      - |
        if ! aws cloudformation describe-type --type RESOURCE --type-name AWSUtility::CloudFormation::CommandRunner >/dev/null 2>&1; then
          git clone https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-awsutilities-commandrunner.git
          cd aws-cloudformation-resource-providers-awsutilities-commandrunner
          curl -LO https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-awsutilities-commandrunner/releases/latest/download/awsutility-cloudformation-commandrunner.zip
          ./scripts/register.sh --set-default
        fi
  build:
    commands:
      - export SAM_CLI_TELEMETRY=0
      - cd ${CODEBUILD_SRC_DIR}
      - npm install
      - sam package --template-file application.yaml --s3-bucket $InfraBucket --output-template-file InfraDeployment.yml 
      # Validate CFN template using cfn-guard
#      - cfn-guard validate -d InfraDeployment.yml -r $CF_ORG_RULESET -S all 
      - aws s3 cp locust-command.py s3://$InfraBucket
      - echo "{\"Parameters\":{\"S3Bucket\":\"$InfraBucket\"},\"Tags\":{\"aws-reinvent-workshop\":\"serverless\"}}" > InfraDeployment.config

artifacts:
    files: 
      - InfraDeployment.yml
      - InfraDeployment.config