version: 0.2
env:
  shell: bash
  variables:
    CF_ORG_RULESET:  "serverless-guard-check"
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - pip install --upgrade aws-sam-cli
      - aws configure set region $AWS_DEFAULT_REGION

  build:
    commands:
      - export SAM_CLI_TELEMETRY=0
      - cd ${CODEBUILD_SRC_DIR}
      - npm install
      - sam package --template-file application.yaml --s3-bucket $InfraBucket --output-template-file InfraDeployment.yml
      - echo "{\"Parameters\":{\"S3Bucket\":\"$InfraBucket\"},\"Tags\":{\"aws-reinvent-workshop\":\"serverless\"}}" > InfraDeployment.config

artifacts:
    files: 
      - InfraDeployment.yml
      - InfraDeployment.config